version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: whatif_main
      POSTGRES_USER: whatif_user
      POSTGRES_PASSWORD: whatif_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - whatif-network

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - whatif-network

volumes:
  postgres_data:

networks:
  whatif-network:
    driver: bridge