version: '3.8'

services:
  # Databases
  postgres:
    image: postgres:15-alpine
    container_name: what-if-postgres
    environment:
      POSTGRES_DB: what_if_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - what-if-network

  mongodb:
    image: mongo:7-jammy
    container_name: what-if-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: what_if_history
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongodb/init.js:/docker-entrypoint-initdb.d/init.js
    networks:
      - what-if-network

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: what-if-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - what-if-network

  # Microservices
  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    container_name: what-if-user-service
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: what_if_users
      DB_USER: postgres
      DB_PASSWORD: postgres123
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      REDIS_URL: redis://redis:6379
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./services/user-service:/app
      - /app/node_modules
    networks:
      - what-if-network

  generation-service:
    build:
      context: ./services/generation-service
      dockerfile: Dockerfile
    container_name: what-if-generation-service
    environment:
      NODE_ENV: development
      PORT: 3002
      GEMINI_API_KEY: your-gemini-api-key-here
      REDIS_URL: redis://redis:6379
      HISTORY_SERVICE_URL: http://history-service:3003
    ports:
      - "3002:3002"
    depends_on:
      - redis
    volumes:
      - ./services/generation-service:/app
      - /app/node_modules
    networks:
      - what-if-network

  history-service:
    build:
      context: ./services/history-service
      dockerfile: Dockerfile
    container_name: what-if-history-service
    environment:
      NODE_ENV: development
      PORT: 3003
      MONGODB_URI: mongodb://admin:admin123@mongodb:27017/what_if_history?authSource=admin
      REDIS_URL: redis://redis:6379
    ports:
      - "3003:3003"
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./services/history-service:/app
      - /app/node_modules
    networks:
      - what-if-network

  sharing-service:
    build:
      context: ./services/sharing-service
      dockerfile: Dockerfile
    container_name: what-if-sharing-service
    environment:
      NODE_ENV: development
      PORT: 3004
      MONGODB_URI: mongodb://admin:admin123@mongodb:27017/what_if_sharing?authSource=admin
      REDIS_URL: redis://redis:6379
    ports:
      - "3004:3004"
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./services/sharing-service:/app
      - /app/node_modules
    networks:
      - what-if-network

  video-service:
    build:
      context: ./services/video-service
      dockerfile: Dockerfile
    container_name: what-if-video-service
    environment:
      NODE_ENV: development
      PORT: 3005
      REDIS_URL: redis://redis:6379
      USER_SERVICE_URL: http://user-service:3001
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      # Google Cloud TTS Configuration
      GOOGLE_APPLICATION_CREDENTIALS: /app/credentials/service-account-key.json
      GOOGLE_CLOUD_PROJECT_ID: your-google-cloud-project-id
      # Video Generation API Keys
      RUNWAY_API_KEY: your-runway-api-key
      PIKA_API_KEY: your-pika-api-key
      STABILITY_API_KEY: your-stability-api-key
      # Feature Flags
      ENABLE_VIDEO_GENERATION: true
      ENABLE_TTS: true
      # Rate Limiting
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
      # File Management
      MAX_FILE_SIZE_MB: 50
      CLEANUP_INTERVAL_HOURS: 24
      # Logging
      LOG_LEVEL: info
      LOG_REQUESTS: true
    ports:
      - "3005:3005"
    depends_on:
      - redis
    volumes:
      - ./services/video-service:/app
      - /app/node_modules
      - video_outputs:/app/outputs
      - video_uploads:/app/uploads
      - video_temp:/app/temp
      # Mount Google Cloud credentials (create this file)
      - ./credentials:/app/credentials:ro
    networks:
      - what-if-network

  social-service:
    build:
      context: ./services/social-service
      dockerfile: Dockerfile
    container_name: what-if-social-service
    environment:
      NODE_ENV: development
      PORT: 3006
      MONGODB_URI: mongodb://admin:admin123@mongodb:27017/what_if_social?authSource=admin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      USER_SERVICE_URL: http://user-service:3001
    ports:
      - "3006:3006"
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./services/social-service:/app
      - /app/node_modules
    networks:
      - what-if-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: what-if-api-gateway
    environment:
      NODE_ENV: development
      PORT: 3000
      USER_SERVICE_URL: http://user-service:3001
      GENERATION_SERVICE_URL: http://generation-service:3002
      HISTORY_SERVICE_URL: http://history-service:3003
      SHARING_SERVICE_URL: http://sharing-service:3004
      VIDEO_SERVICE_URL: http://video-service:3005
      SOCIAL_SERVICE_URL: http://social-service:3006
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      REDIS_URL: redis://redis:6379
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - generation-service
      - history-service
      - sharing-service
      - video-service
      - social-service
      - redis
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    networks:
      - what-if-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: what-if-frontend
    environment:
      REACT_APP_API_URL: http://localhost:3000
      REACT_APP_ENVIRONMENT: development
    ports:
      - "3005:3000"
    depends_on:
      - api-gateway
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - what-if-network

volumes:
  postgres_data:
  mongodb_data:
  redis_data:
  video_outputs:
  video_uploads:
  video_temp:

networks:
  what-if-network:
    driver: bridge